name: Force Refresh updated_at

on:
  schedule:
    - cron: '1 16 * * *'  # UTC 16:01 = 北京时间 00:01
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # 让 GITHUB_TOKEN 能用于 push

      - name: Write UTC timestamp to file
        run: |
          mkdir -p .github
          echo "Last updated: $(date -u)" > .github/updated.txt
          
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "139797821+wuabai@users.noreply.github.com"
          git add .github/updated.txt
          git commit -m "chore: force update timestamp $(date -u) [skip ci]" || echo "Nothing to commit"
          git push
